name: gorevde_yukselme
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # UI Components
  google_fonts: ^6.2.1
  
  # Charts for Performance Analysis
  fl_chart: ^0.68.0
  
  # Icons
  cupertino_icons: ^1.0.8
  
  # Navigation
  go_router: ^14.2.7
  
  # Utilities
  equatable: ^2.0.5
  
  # URL Launcher
  url_launcher: ^6.3.1
  
  # HTTP Client
  http: ^1.2.2
  
  # Storage
  shared_preferences: ^2.3.2
  
  # Device Info
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  
  # Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # In-App Purchases
  in_app_purchase: ^3.2.3
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  google_sign_in: ^6.2.1
  
  # AdMob
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.3.13
  
  # Testing
  mockito: ^5.4.4
  
  # Code Generation
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/gyudIcon.jpeg"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
