// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAamwJpFNQmspHrP4CnIwzWOxG7tiCkfF0',
    appId: '1:933845628166:web:759b569ae611d960219a87',
    messagingSenderId: '933845628166',
    projectId: 'gorevdeyukselme-3d32f',
    authDomain: 'gorevdeyukselme-3d32f.firebaseapp.com',
    storageBucket: 'gorevdeyukselme-3d32f.firebasestorage.app',
    measurementId: 'G-VTCESRTPRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDznwathzmuxalrSiXhIzpyQdc4QNUnB08',
    appId: '1:933845628166:android:d477038a7946c986219a87',
    messagingSenderId: '933845628166',
    projectId: 'gorevdeyukselme-3d32f',
    storageBucket: 'gorevdeyukselme-3d32f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2jc9AzqFsXsbli1_r7b0kBeILtkG7pQU',
    appId: '1:933845628166:ios:4747ba3515a29240219a87',
    messagingSenderId: '933845628166',
    projectId: 'gorevdeyukselme-3d32f',
    storageBucket: 'gorevdeyukselme-3d32f.firebasestorage.app',
    iosBundleId: 'com.gyudsoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2jc9AzqFsXsbli1_r7b0kBeILtkG7pQU',
    appId: '1:933845628166:ios:e8931c87a9d2d185219a87',
    messagingSenderId: '933845628166',
    projectId: 'gorevdeyukselme-3d32f',
    storageBucket: 'gorevdeyukselme-3d32f.firebasestorage.app',
    iosBundleId: 'com.example.gorevdeYukselme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAamwJpFNQmspHrP4CnIwzWOxG7tiCkfF0',
    appId: '1:933845628166:web:6c65ab6a223ec307219a87',
    messagingSenderId: '933845628166',
    projectId: 'gorevdeyukselme-3d32f',
    authDomain: 'gorevdeyukselme-3d32f.firebaseapp.com',
    storageBucket: 'gorevdeyukselme-3d32f.firebasestorage.app',
    measurementId: 'G-X6PR52N5QR',
  );

}